version: 1
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          update_type: security
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
    version_requirement_updates: widen_ranges